site_name: JeKa Build Tool
theme:
    name: material
    highlight_theme: dracula
    logo: images/logo-plain-white.svg
    favicon: images/logo-plain-gradient.svg
    font:
      text: 'Inter'
      code: 'Fire Code'
    palette :
      # Palette toggle for light mode
      # Palette toggle for dark mode
      - scheme: default
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode
        primary: 'deep purple'
        accent: 'purple'
        
      - scheme: slate
        toggle:
          icon: material/brightness-4
          name: Switch to light mode
        primary: 'deep purple'
        accent: 'purple'
        favicon: images/knight-color-logo.svg

    features:
        - navigation.instant
        - navigation.tracking
        - content.code.copy
extra:
    analytics:
        provider: google
        property: UA-103449580-2

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
      line_spans: __span
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
    - Installation: installation.md
    - Tutorials:
        - Basics: tutorials/basics.md
        - Build Base: tutorials/build-base.md
        - Build Projects: tutorials/build-projects.md
    - Reference:
        - KBeans: reference/kbeans.md
        - Properties: reference/properties.md
        - Build Library:
            - Project: reference/api-project.md
            - Native: reference/api-native.md
            - Docker: reference/api-docker.md
            - Git: reference/api-git.md
            - Dependency Management: reference/api-dependency-management.md
    - Cheat Sheet: cheat-sheet.md
    - FAQ: faq.md
    - Examples: examples.md
    - External Resources: external-resources.md
    - Javadoc: javadoc/
    - Under The Hood: under-the-hood.md

repo_url: https://github.com/jerkar/jeka

extra_css:
  - stylesheets/extra.css
