site_name: Jeka Build Tool
theme:
    name: material
    palette :
        primary: blue
    favicon: images/favicon.ico
    features:
        - navigation.instant
        - navigation.tracking
        - navigation.expand
        #- toc.integrate
extra:
    analytics:
        provider: google
        property: UA-103449580-2
nav:
    - Reference Guide:
        - Abstract : index.md
        - Execution Engine:
          - File Structure: execution-engine-files.md
          - Setup: execution-engine-setup.md
          - Concepts: execution-engine-concepts.md
        - Build Library: build-library.md
    - Cheat Sheet: cheat-sheet.md
repo_url: https://github.com/jerkar/jeka
markdown_extensions:
    - admonition
    - toc:
        permalink: true
    - pymdownx.superfences
    - pymdownx.highlight:
        anchor_linenums: true
