site_name: Jeka Build Tool
theme:
    name: material
    logo: images/logo.svg
    palette :
        primary: blue
    favicon: images/favicon.ico
    features:
        - navigation.instant
        - navigation.tracking
extra:
    analytics:
        provider: google
        property: UA-103449580-2
nav:
    - Reference Guide:
        - Execution Engine:
          - File Structure: reference-guide/execution-engine-files.md
          - Setup: reference-guide/execution-engine-setup.md
          - Concepts: reference-guide/execution-engine-concepts.md
          - Process: reference-guide/execution-engine-process.md
          - Reuse Elements: reference-guide/execution-engine-reuse.md
        - Build Library:
          - Style: reference-guide/build-library-style.md
          - System: reference-guide/build-library-system.md
          - File Management: reference-guide/build-library-files.md
          - Delependency Management: reference-guide/build-library-dependency-management.md
          - Project Build: reference-guide/build-library-project-build.md
          - 3rd Party Tool Integration: reference-guide/build-library-3rd-party-tool-integration.md
    - Tutorials IntelliJ Plugin:
        - Getting Started: tutorials/gui-getting-started.md
        - Reuse Elements: tutorials/gui-reuse-elements.md
    - Cheat Sheet: cheat-sheet.md
    - FAQ: faq.md
    - Examples: examples.md
repo_url: https://github.com/jerkar/jeka
markdown_extensions:
    - admonition
    - toc:
        permalink: true
    - pymdownx.superfences
    - pymdownx.highlight:
        anchor_linenums: true
