site_name: JeKa Build Tool
theme:
    name: material
    logo: images/logo.svg
    favicon: images/knight-color-logo.svg
    font:
      text: Roboto
    palette :
      # Palette toggle for light mode
      # Palette toggle for dark mode
      - scheme: slate
        toggle:
          icon: material/brightness-4
          name: Switch to light mode
        primary: purple
        favicon: images/knight-color-logo.svg

      - scheme: default
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode
        primary: purple
        accent: indigo


    features:
        - navigation.instant
        - navigation.tracking
        - content.code.copy
extra:
    analytics:
        provider: google
        property: UA-103449580-2
nav:
    - Installation: installation.md
    - Tutorials:
        - Getting Started: tutorials/getting-started.md
        - Build Projects: tutorials/build-projects.md
    - Reference:
        - KBeans: reference/kbeans.md
        - Properties: reference/properties.md
    - Cheat Sheet: cheat-sheet.md
    - FAQ: faq.md
    - Examples: examples.md
    - Migration Guide (0.10 -> 0.11): migration-guide.md
    - Legacy (version  0.10.x) :
      - Reference Guide:
          - Execution Engine:
            - File Structure: legacy/reference-guide/execution-engine-files.md
            - Setup: legacy/reference-guide/execution-engine-setup.md
            - Def-Classpath: legacy/reference-guide/execution-engine-defclasspath.md
            - KBeans: legacy/reference-guide/execution-engine-kbeans.md
            - Properties: legacy/reference-guide/execution-engine-properties.md
            - Process: legacy/reference-guide/execution-engine-process.md
            - Reuse Elements: legacy/reference-guide/execution-engine-reuse.md
          - Build Library:
            - Intro: legacy/reference-guide/build-library-intro.md
            - System: legacy/reference-guide/build-library-system.md
            - File Management: legacy/reference-guide/build-library-files.md
            - Dependency Management: legacy/reference-guide/build-library-dependency-management.md
            - Project Build: legacy/reference-guide/build-library-project-build.md
            - 3rd Party Tool Integration: legacy/reference-guide/build-library-3rd-party-tool-integration.md
      - Tutorials IntelliJ Plugin:
          - Getting Started: legacy/tutorials/gui-getting-started.md
          - Reuse Elements: legacy/tutorials/gui-reuse-elements.md
      - Faq: legacy/faq.md

repo_url: https://github.com/jerkar/jeka
markdown_extensions:
    - admonition
    - toc:
        permalink: true
    - pymdownx.superfences
    - pymdownx.highlight:
        anchor_linenums: true
